### ISSUE TITLE
可否适当在源码中添加一些注释，阅读起来相当费力

### ISSUE THREAD

**Issue by ayonel** [Meituan-Dianping/octo-rpc#2]
如题，没有注释，啃源码太难了。。

**Comment by YangruiEmma** [comment]
您好，谢谢反馈，请问您具体看的是Java RPC还是C++ RPC呢

**Comment by ayonel** [comment]
> 您好，谢谢反馈，请问您具体看的是Java RPC还是C++ RPC呢

目前再看java, 注释很少，看起来比较吃力。还是建议增加些注释，提高下对新手的友好度。

**Comment by YangruiEmma** [comment]
好的，之后更新尽量完善注释，建议关注 [框架的介绍](https://github.com/Meituan-Dianping/octo-rpc/wiki/OCTO-Dorado%E9%80%9A%E4%BF%A1%E6%A1%86%E6%9E%B6%E4%BB%8B%E7%BB%8D) 里面有框架设计的说明
