### ISSUE TITLE
origin thrift Java client can't invoke a octo service

### ISSUE THREAD

**Issue by icebergger** [Meituan-Dianping/octo-rpc#6]
Hi，

I have a origin thrift java client, but can't invoke the octo service as well.
the client code is blocked in line " echo = client.echo("11111");" 

client code：

`public class OriginThriftClient {

     public static void main(String[] args) {

        TTransport transport = null;
        try {
            transport = new TFramedTransport(new TSocket("localhost", 9001));
            transport.open();

            TProtocol protocol = new TBinaryProtocol(transport);
            Echo.Iface client = new Echo.Client(protocol);
            String echo = client.echo("abc");
            System.out.println(echo);

             echo = client.echo("11111");
            System.out.println(echo);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            transport.close();
            ServiceBootstrap.clearGlobalResource();
        }
    }
}`

server code：
com.meituan.dorado.testserver.ServerMain   in module dorado-test-server

**Comment by YangruiEmma** [comment]
Thanks very much, I have fixed it. And add a test case, you can run `OriginThriftTest` in `dorado-test-integration `module
