### ISSUE TITLE
Consumer programs cannot exit automatically

### ISSUE THREAD

**Issue by 1522140840** [Meituan-Dianping/octo-rpc#7]
I found that this is not a daemon thread. When I change to a daemon thread, I can automatically exit.
https://github.com/Meituan-Dianping/octo-rpc/blob/ece7bd791d5e8608473e6a17a2624bc409738c9c/dorado/dorado-transport/dorado-transport-netty/src/main/java/com/meituan/dorado/transport/netty/NettyClient.java#L41
https://github.com/Meituan-Dianping/octo-rpc/blob/ece7bd791d5e8608473e6a17a2624bc409738c9c/dorado/dorado-core/src/main/java/com/meituan/dorado/bootstrap/invoker/ServiceInvocationRepository.java#L55

Direct output error？
https://github.com/Meituan-Dianping/octo-rpc/blob/ece7bd791d5e8608473e6a17a2624bc409738c9c/dorado/dorado-registry/dorado-registry-zookeeper/src/main/java/com/meituan/dorado/registry/zookeeper/curator/ZookeeperClient.java#L217

**Comment by YangruiEmma** [comment]
Thank you very much!
thread `DoradoClientNettyWorkerGroup` and `DoradoTimeoutScheduler` have adjust to daemon
the log level also has been updated. ; ）
